name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    name: Tests stage
    runs-on: ubuntu-latest

    steps:
      - name: Unit test
        run: echo "Here comes the unit tests..."

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Debug
        run: echo $PWD; ls -l 

      - name: Install dependencies
        run: |
          cd ./sre/download_service/
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit tests
        run: pytest --cov --cov-report term-missing

  build:
    needs: test
    name: Build and publish stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Prepare environment
        run: cd ./sre/download_service/; ls -l

      #- name: Check Dockerfile
      #  run: docker run --rm -i hadolint/hadolint < Dockerfile

      - name: Build docker image
        run: ls -l; docker build -t maurobaraldi/download-service ./sre/download_service/

      - name: Push docker image
        run: docker push maurobaraldi/download-service

  publish:
    needs: build
    name: Release stage
    runs-on: ubuntu-latest

    steps:
      - name: Publish package
        run: echo "Publish the package for deploy."
