name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    name: Tests stage
    runs-on: ubuntu-latest

    steps:
      - name: Unit test
        run: echo "Here comes the unit tests..."

  build:
    needs: test
    name: Build and publish stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./sre/download_service/requirements.txt
      
      - name: Checkout Repository
        run: cd ./sre/download-service/; pytest --cov --cov-report term-missing

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Dockerfile
        run: docker run --rm -i hadolint/hadolint < ./sre/download-service/Dockerfile

      - name: Build docker image
        run: docker build -t maurobaraldi/download-service:latest ./sre/download-service

      - name: Push docker image
        run: docker push maurobaraldi/download-service:latest

  publish:
    needs: build
    name: Release stage
    runs-on: ubuntu-latest

    steps:
      - name: Publish package
        run: echo "Publish the package for deploy."
